#!/bin/bash

# Railway Deployment Helper
# This guides you through deploying Tekvoro to Railway

echo "╔════════════════════════════════════════════╗"
echo "║   TEKVORO RAILWAY DEPLOYMENT               ║"
echo "║   Easiest & Fastest Production Option      ║"
echo "╚════════════════════════════════════════════╝"
echo ""

echo "📋 STEP 1: Verify Your GitHub Repository"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
git log -1 --oneline
echo ""
echo "✓ Your code is ready at: $(git remote get-url origin)"
echo ""

echo "📋 STEP 2: Create Railway Account & Connect GitHub"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Go to: https://railway.app"
echo "2. Click 'Create New Project'"
echo "3. Select 'Deploy from GitHub'"
echo "4. Authorize Railway to access your GitHub account"
echo "5. Select this repository: tekvoro-web"
echo "6. Select branch: main"
echo ""
read -p "Press ENTER after selecting your repository in Railway..."
echo ""

echo "📋 STEP 3: Configure Environment Variables"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "In Railway Dashboard → Project Settings → Variables:"
echo ""
echo "Add these variables:"
echo ""
echo "  NODE_ENV=production"
echo "  PORT=5002"
echo "  MONGODB_URI=mongodb+srv://user:password@cluster.mongodb.net/tekvoro"
echo "  JWT_SECRET=$(openssl rand -base64 32 2>/dev/null || echo '<paste-strong-secret>')"
echo "  SENDGRID_API_KEY=<your-sendgrid-key>"
echo ""
echo "Important: You'll need:"
echo "  • MongoDB Atlas connection string"
echo "  • SendGrid API key"
echo "  • A strong JWT secret"
echo ""
read -p "Press ENTER after setting all environment variables..."
echo ""

echo "📋 STEP 4: Monitor Deployment"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Railway will automatically:"
echo "  ✓ Detect the Dockerfile"
echo "  ✓ Build the Docker image"
echo "  ✓ Deploy to production"
echo "  ✓ Generate a live URL"
echo ""
echo "Watch the logs in Railway dashboard:"
echo "  Settings → Deployments → Logs"
echo ""
echo "Deployment usually takes 3-5 minutes."
echo ""
read -p "Press ENTER after deployment completes..."
echo ""

echo "📋 STEP 5: Verify Deployment"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Enter your Railway domain (without https://):"
read -p "> " RAILWAY_DOMAIN
echo ""

# Test the API
echo "Testing API health endpoint..."
HEALTH_RESPONSE=$(curl -s "${RAILWAY_DOMAIN}/api/health" 2>&1)
echo "Response: $HEALTH_RESPONSE"
echo ""

if echo "$HEALTH_RESPONSE" | grep -q "OK\|status"; then
    echo "✅ API is responding!"
else
    echo "⚠️  API not responding yet. Check:"
    echo "  • Environment variables are set correctly"
    echo "  • MongoDB connection string is valid"
    echo "  • Deployment logs for errors"
fi
echo ""

echo "📋 STEP 6: Setup Custom Domain (Optional)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "In Railway Dashboard → Project Settings → Domains:"
echo ""
echo "1. Click 'Add Domain'"
echo "2. Enter: www.tekvoro.com (or your domain)"
echo "3. Railway generates a CNAME record"
echo "4. Add CNAME to your DNS provider"
echo "5. Wait 5-10 minutes for DNS propagation"
echo ""
echo "Your domain: https://www.tekvoro.com"
echo ""

echo "╔════════════════════════════════════════════╗"
echo "║   🎉 DEPLOYMENT COMPLETE!                  ║"
echo "╚════════════════════════════════════════════╝"
echo ""
echo "✅ Your Tekvoro site is now LIVE!"
echo ""
echo "Next Steps:"
echo "  1. Create admin user (see ADMIN_SETUP_GUIDE.md)"
echo "  2. Test features on production"
echo "  3. Monitor logs and errors"
echo "  4. Setup backups in MongoDB Atlas"
echo ""
echo "For help:"
echo "  • QUICK_DEPLOY.md - Quick reference"
echo "  • PRODUCTION_DEPLOYMENT.md - Detailed guide"
echo "  • ADMIN_SETUP_GUIDE.md - Admin configuration"
echo ""
